// weapons.ts
const assualtRefile = [
  {
    category: "assault rifle",
    sketchFabUrl:
      '<div class="sketchfab-embed-wrapper"> <iframe title="HK416 Full ReWorked" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share width="640" height="480" src="https://sketchfab.com/models/669a9ee17dc44580b53425a08c2f83d0/embed?ui_theme=dark"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/hk416-full-reworked-669a9ee17dc44580b53425a08c2f83d0?utm_medium=embed&utm_campaign=share-popup&utm_content=669a9ee17dc44580b53425a08c2f83d0" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> HK416 Full ReWorked </a> by <a href="https://sketchfab.com/moco80?utm_medium=embed&utm_campaign=share-popup&utm_content=669a9ee17dc44580b53425a08c2f83d0" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> MojoLeeDa </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=669a9ee17dc44580b53425a08c2f83d0" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>',
  },
  {
    category: "assault rifle",
    sketchFabUrl:
      '<div class="sketchfab-embed-wrapper"> <iframe title="AK-47" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/ZMhWW9znpiBAhxDSomqX2kSSfg/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/ak-47-ZMhWW9znpiBAhxDSomqX2kSSfg?utm_medium=embed&utm_campaign=share-popup&utm_content=ZMhWW9znpiBAhxDSomqX2kSSfg" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> AK-47 </a> by <a href="https://sketchfab.com/millenia3d?utm_medium=embed&utm_campaign=share-popup&utm_content=ZMhWW9znpiBAhxDSomqX2kSSfg" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Azure Midsummer (millenia3d) </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=ZMhWW9znpiBAhxDSomqX2kSSfg" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>',
  },
  {
    category: "assault rifle",
    sketchFabUrl:
      '<div class="sketchfab-embed-wrapper"> <iframe title="AK-74" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/44c6581b852a4a03a0cd509be06f0dd8/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/ak-74-44c6581b852a4a03a0cd509be06f0dd8?utm_medium=embed&utm_campaign=share-popup&utm_content=44c6581b852a4a03a0cd509be06f0dd8" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> AK-74 </a> by <a href="https://sketchfab.com/dimalukomo?utm_medium=embed&utm_campaign=share-popup&utm_content=44c6581b852a4a03a0cd509be06f0dd8" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> madridista_9248 </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=44c6581b852a4a03a0cd509be06f0dd8" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>',
  },
  {
    category: "assault rifle",
    sketchFabUrl:
      '<div class="sketchfab-embed-wrapper"> <iframe title="AK 103" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/863dbd7b0aa54a839ccdfe43d98c778a/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/ak-103-863dbd7b0aa54a839ccdfe43d98c778a?utm_medium=embed&utm_campaign=share-popup&utm_content=863dbd7b0aa54a839ccdfe43d98c778a" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> AK 103 </a> by <a href="https://sketchfab.com/Frostoise?utm_medium=embed&utm_campaign=share-popup&utm_content=863dbd7b0aa54a839ccdfe43d98c778a" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Frostoise </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=863dbd7b0aa54a839ccdfe43d98c778a" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>',
  },
  {
    category: "assault rifle",
    sketchFabUrl:
      '<div class="sketchfab-embed-wrapper"> <iframe title="M16" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/147ac478e4714c0a9ba3e10eabf0bd75/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/m16-147ac478e4714c0a9ba3e10eabf0bd75?utm_medium=embed&utm_campaign=share-popup&utm_content=147ac478e4714c0a9ba3e10eabf0bd75" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> M16 </a> by <a href="https://sketchfab.com/Frostoise?utm_medium=embed&utm_campaign=share-popup&utm_content=147ac478e4714c0a9ba3e10eabf0bd75" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Frostoise </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=147ac478e4714c0a9ba3e10eabf0bd75" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>',
  },
  {
    category: "assault rifle",
    sketchFabUrl:
      '<div class="sketchfab-embed-wrapper"> <iframe title="M4 Carbine" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/b516a8416b1044a7839b4a89dc24ca38/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/m4-carbine-b516a8416b1044a7839b4a89dc24ca38?utm_medium=embed&utm_campaign=share-popup&utm_content=b516a8416b1044a7839b4a89dc24ca38" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> M4 Carbine </a> by <a href="https://sketchfab.com/sinnik?utm_medium=embed&utm_campaign=share-popup&utm_content=b516a8416b1044a7839b4a89dc24ca38" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> SINNIK </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=b516a8416b1044a7839b4a89dc24ca38" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>',
  },
  {
    category: "assault rifle",
    sketchFabUrl:
      '<div class="sketchfab-embed-wrapper"> <iframe title="HK416 Full ReWorked" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/669a9ee17dc44580b53425a08c2f83d0/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/hk416-full-reworked-669a9ee17dc44580b53425a08c2f83d0?utm_medium=embed&utm_campaign=share-popup&utm_content=669a9ee17dc44580b53425a08c2f83d0" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> HK416 Full ReWorked </a> by <a href="https://sketchfab.com/moco80?utm_medium=embed&utm_campaign=share-popup&utm_content=669a9ee17dc44580b53425a08c2f83d0" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> MojoLeeDa </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=669a9ee17dc44580b53425a08c2f83d0" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>',
  },
  {
    category: "assault rifle",
    sketchFabUrl:
      '<div class="sketchfab-embed-wrapper"> <iframe title="Low-Poly FN SCAR H" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/c52bc2a8ddaa47caa34e94d69ff72d96/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/low-poly-fn-scar-h-c52bc2a8ddaa47caa34e94d69ff72d96?utm_medium=embed&utm_campaign=share-popup&utm_content=c52bc2a8ddaa47caa34e94d69ff72d96" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Low-Poly FN SCAR H </a> by <a href="https://sketchfab.com/TastyTony?utm_medium=embed&utm_campaign=share-popup&utm_content=c52bc2a8ddaa47caa34e94d69ff72d96" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> TastyTony </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=c52bc2a8ddaa47caa34e94d69ff72d96" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>',
  },
  {
    category: "assault rifle",
    sketchFabUrl:
      '<div class="sketchfab-embed-wrapper"> <iframe title="G36 with attachments" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/de744d8804ce4231ba3c76f791980832/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/g36-with-attachments-de744d8804ce4231ba3c76f791980832?utm_medium=embed&utm_campaign=share-popup&utm_content=de744d8804ce4231ba3c76f791980832" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> G36 with attachments </a> by <a href="https://sketchfab.com/frankestudios71?utm_medium=embed&utm_campaign=share-popup&utm_content=de744d8804ce4231ba3c76f791980832" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Kelisei Ventura </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=de744d8804ce4231ba3c76f791980832" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>',
  },
  {
    category: "assault rifle",
    sketchFabUrl:
      '<div class="sketchfab-embed-wrapper"> <iframe title="Low-Poly Tavor Tar-21" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/42ce28f1f3594cc58c80ae276e337eb5/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/low-poly-tavor-tar-21-42ce28f1f3594cc58c80ae276e337eb5?utm_medium=embed&utm_campaign=share-popup&utm_content=42ce28f1f3594cc58c80ae276e337eb5" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Low-Poly Tavor Tar-21 </a> by <a href="https://sketchfab.com/TastyTony?utm_medium=embed&utm_campaign=share-popup&utm_content=42ce28f1f3594cc58c80ae276e337eb5" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> TastyTony </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=42ce28f1f3594cc58c80ae276e337eb5" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>',
  },
  {
    category: "assault rifle",
    sketchFabUrl:
      '<div class="sketchfab-embed-wrapper"> <iframe title="FAMAS" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/7d35e14ad8874d148ce9cc46e5765a6b/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/famas-7d35e14ad8874d148ce9cc46e5765a6b?utm_medium=embed&utm_campaign=share-popup&utm_content=7d35e14ad8874d148ce9cc46e5765a6b" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> FAMAS </a> by <a href="https://sketchfab.com/Frostoise?utm_medium=embed&utm_campaign=share-popup&utm_content=7d35e14ad8874d148ce9cc46e5765a6b" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Frostoise </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=7d35e14ad8874d148ce9cc46e5765a6b" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>',
  },
  {
    category: "assault rifle",
    sketchFabUrl:
      '<div class="sketchfab-embed-wrapper"> <iframe title="Low-Poly CZ 805 Bren" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/ffc93e9963ab4566b8908f57209f98a1/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/low-poly-cz-805-bren-ffc93e9963ab4566b8908f57209f98a1?utm_medium=embed&utm_campaign=share-popup&utm_content=ffc93e9963ab4566b8908f57209f98a1" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Low-Poly CZ 805 Bren </a> by <a href="https://sketchfab.com/TastyTony?utm_medium=embed&utm_campaign=share-popup&utm_content=ffc93e9963ab4566b8908f57209f98a1" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> TastyTony </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=ffc93e9963ab4566b8908f57209f98a1" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>',
  },
  {
    category: "assault rifle",
    sketchFabUrl:
      '<div class="sketchfab-embed-wrapper"> <iframe title="L85 - Sa80" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/44cdbdce36a343e9bf2d6261b166c73a/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/l85-sa80-44cdbdce36a343e9bf2d6261b166c73a?utm_medium=embed&utm_campaign=share-popup&utm_content=44cdbdce36a343e9bf2d6261b166c73a" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> L85 - Sa80 </a> by <a href="https://sketchfab.com/Jamoues?utm_medium=embed&utm_campaign=share-popup&utm_content=44cdbdce36a343e9bf2d6261b166c73a" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Jamoues </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=44cdbdce36a343e9bf2d6261b166c73a" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>',
  },
  {
    category: "assault rifle",
    sketchFabUrl:
      '<div class="sketchfab-embed-wrapper"> <iframe title="Galil Ace" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/5471bfc3d66a402f8eb4fda52b62a2df/embed"> </iframe> <p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;"> <a href="https://sketchfab.com/3d-models/galil-ace-5471bfc3d66a402f8eb4fda52b62a2df?utm_medium=embed&utm_campaign=share-popup&utm_content=5471bfc3d66a402f8eb4fda52b62a2df" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> Galil Ace </a> by <a href="https://sketchfab.com/mark7levin?utm_medium=embed&utm_campaign=share-popup&utm_content=5471bfc3d66a402f8eb4fda52b62a2df" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;"> MarkLevin </a> on <a href="https://sketchfab.com?utm_medium=embed&utm_campaign=share-popup&utm_content=5471bfc3d66a402f8eb4fda52b62a2df" target="_blank" rel="nofollow" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a></p></div>',
  },
];
export default assualtRefile;
